# Generated by Django 4.2.2 on 2024-01-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_sprint_profile_epic_task_epic"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sprint",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="end_date_after_start_date",
            ),
        ),
    ]
