# Generated by Django 4.2.2 on 2024-02-01 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0006_task_status_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"permissions": [("custom_task", "Custom Task Permission")]},
        ),
        migrations.AlterModelTableComment(
            name="task",
            table_comment=None,
        ),
        migrations.RemoveField(
            model_name="task",
            name="epic",
        ),
        migrations.AddField(
            model_name="epic",
            name="completion_status",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="epic",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="epics", to="tasks.task"
            ),
        ),
        migrations.AddField(
            model_name="sprint",
            name="epic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sprints",
                to="tasks.epic",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="file_upload",
            field=models.FileField(blank=True, null=True, upload_to="tasks/files/"),
        ),
        migrations.AddField(
            model_name="task",
            name="image_upload",
            field=models.ImageField(blank=True, null=True, upload_to="tasks/images/"),
        ),
        migrations.AddField(
            model_name="task",
            name="version",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unassigned", "Unassigned"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Done"),
                    ("Archived", "Archived"),
                ],
                default="Unassigned",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.AddField(
            model_name="email",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchers",
                to="tasks.task",
            ),
        ),
    ]
